### ISSUE TITLE
Notification and Pre/Post pipeline similar to MediaR

### ISSUE THREAD

**Issue by girish66** [m4ss1m0g/mediatr-ts#1]
Is there a notification and pre/post pipeline similar to MediaR? If so can you please share an example.

**Comment by m4ss1m0g** [comment]
Unfortunately not yet, I'm working on it.

**Comment by m4ss1m0g** [comment]
@girish66 I have implemented the Notification pattern for now **without** Pre/Post pipeline

**Comment by girish66** [comment]
Thank you will try it out.
