### ISSUE TITLE
Graphql and Mediatr-ts

### ISSUE THREAD

**Issue by girish66** [m4ss1m0g/mediatr-ts#2]
Hello I am using your library with Graphql, however I am getting an unresolvable error below is how I am loading the container, but the error being thrown is that the no resolvers can be found? can you point to what I am doing incorrectly? 
``` typescript
/**
 * ApplicationContainer.
 */
class ApplicationContainer extends Container {
    // Constructor.
    constructor() {
        super({ skipBaseClassChecks: true, autoBindInjectable: true});
        //mediatorSettings.resolver = new MediatrResolver();
        this.load();
    }
}

// create the applicationContainer
const applicationContainer = new ApplicationContainer();

// Implement the resolver
class MediatrResolver implements IResolver {
    /**
     *  Resolve.
     * @param name
     */
    resolve<T>(name: string): T {
        return applicationContainer.get(name);
    }

    /**
     * Add.
     * @param name
     * @param instance
     */
    add(name: string, instance: Function): void {
        applicationContainer.bind(name).to(instance as any);
    }

    /**
     * Remove.
     * @param name
     */
    remove(name: string): void {
        // not necessary- can be blank, never called by the lib, for debugging / testing only
        applicationContainer.unbind(name);
    }

    /**
     * Clear.
     */
    clear(): void {
        // not necessary- can be blank, never called by the lib, for debugging / testing only
        applicationContainer.unbindAll();
    }
}

// Set mediatr to use the resolver
mediatorSettings.resolver = new MediatrResolver();

// bind utilities
Utilities.bind(applicationContainer);
// bind repositories
Repositories.bind(applicationContainer);
// bind services
Services.bind(applicationContainer);
// bind GraphQL context
Context.bind(applicationContainer);

// export container.
export { applicationContainer };
```

**Comment by m4ss1m0g** [comment]
Try to move `mediatorSettings.resolver = new MediatrResolver();` at the beginning of the application like this:

```typescript
import settings from "@/models/settings";
import MediatrResolver from "whatever";

settings.resolver = new MediatrResolver ();
```

If you don't resolve, try to post a tree of the app with the sequences of calls

**Comment by girish66** [comment]
I have shared the codebase with you.

**Comment by m4ss1m0g** [comment]
I pushed a _FixContainer_ branch: I've already said on docs that the mediator settings MUST BE configured and assigned BEFORE import ANY of the _RequestHandler_ class, otherwise it not found the container.

Run `npm run dev` open the _http://localhost:61010/meditar_  and check the console to see the load/import sequence:

1. First of all create a container, DO NOT IMPORT ANY RequestHandler's class
2. Import resolver
3. Create the resolver with the container instance
4. Import Request Handler now found the resolver and inversify container and it is register to the container

**Comment by girish66** [comment]
Thank you I was missing the loading the container part. This resolved the issue.
