### ISSUE TITLE
Resolver.add throwing Error could break in some Hot Reloaders

### ISSUE THREAD

**Issue by josemarcilio** [m4ss1m0g/mediatr-ts#24]
Currently I'm experimenting Mediatr TS with Remix, and I think I got a problem with Hot Reload. I receive:
```
Error: The key GetFilterableMakesCommand is already been added
    at Resolver.add (file:///home/zbradev06/Source/cars/node_modules/.pnpm/mediatr-ts@1.2.1/node_modules/mediatr-ts/src/models/resolver.ts:45:20)
```

for my decorated class:
```ts
@requestHandler(GetFilterableMakesCommand)
export class GetFilterableMakesCommandHandler {}
```

for each code update and hot reload. It works perfectly using the app normally.

IMHO throwing here is unnecessary. I think there's no reason to break the program for an already registered RequestHandler, especially if we can´t catch this error with a good experience.

I am using pnpm so I can patch locally, and I'll change the throw for a console.error or some similar solution. 

Also I can open a PR with this change if this is an acceptable solution for the project.

**Comment by m4ss1m0g** [comment]
Try to write the necessary code and the relative unit tests, then open a PR.
Thanks.
