### ISSUE TITLE
Can I become a contributor?

### ISSUE THREAD

**Issue by ffMathy** [m4ss1m0g/mediatr-ts#6]
I think I could really add value to this repo and make sure that there is support and coverage of more features.

**Comment by m4ss1m0g** [comment]
Hi @ffMathy, thank you for your offer I really appreciate it. What kind of features do you think to add to the project? Since you have also requested the implementation for IPipelineBehaviour, do you consider implementing it? Can you submit a PR?
Many thanks

**Comment by ffMathy** [comment]
Yes, that's one of the things I had in mind 😊

I'll submit a PR then 🙏

**Comment by ffMathy** [comment]
@m4ss1m0g first PR created. After that is merged, I'll create a lot more functionality.
